version: '3.8'

networks:
  app-network:
    driver: bridge

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    networks:
      - app-network
  broker:
    image: redis:latest
    restart: always
    networks:
      - app-network
